version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: cargo
    directory: /sdk
    schedule:
      interval: weekly

  - package-ecosystem: cargo
    directory: /onchain
    schedule:
      interval: weekly

  - package-ecosystem: pub
    directory: /apps/smart_congrats_app
    schedule:
      interval: weekly

  - package-ecosystem: pub
    directory: /apps/smart_congrats_app/packages/presentation
    schedule:
      interval: weekly

